name: Code health check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build and check code
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
         distribution: adopt
         java-version: 11

      - name: Build an APK
        run: ./gradlew :app:assembleDebug

      - name: Check code
        run: ./gradlew detekt

      - name: Upload detekt report
        uses: actions/upload-artifact@v2
        with:
          name: detekt-report
          path: ./**/detekt.html

      - name: Run Android Lint
        run: ./gradlew lintDebug

      - name: Upload lint report
        uses: actions/upload-artifact@v2
        with:
          name: lint-report
          path: ./**/lint-results-debug.html
